=== latrare/school-monorepo/cs548/assignments/assignment-3/tmiranda_Assignment3/Assignment3-Xquery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://cs548.stevens.edu/clinic/db" elementFormDefault="unqualified"
    xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cs548.stevens.edu/clinic/db"
    attributeFormDefault="unqualified">
    
    <element name="clinic">
        <complexType>
        <sequence>
            <element name="patient" type="tns:patient-type" minOccurs="0" maxOccurs="unbounded"/>
        </sequence></complexType>
    </element>
    
    <complexType name="patient-type">
        <sequence>
            <element name="patient-id" type="long"/>
            <element name="name" type="string"/>
            <element name="treatment" type="tns:drug-treatment-type" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <complexType name="provider-type">
        <sequence>
            <element name="npi" type="string"/>
            <element name="name" type="string"/>
        </sequence>
    </complexType>
    
    <complexType name="drug-treatment-type">
        <sequence>
            <element name="id" type="long"/>
            <element name="diagnosis" type="string"/>
            <element name="drug" type="string"/>
            <element name="provider" type="tns:provider-type"/>
        </sequence>
    </complexType>

</schema>

=== latrare/school-monorepo/cs548/assignments/assignment-3/tmiranda_Assignment3/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Trevor Miranda -->
<tns:clinic xmlns:tns="http://cs548.stevens.edu/clinic/db" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cs548.stevens.edu/clinic/db file:/home/canis/Projects/school-monorepo/cs548/assignments/assignment-3/Assignment3-Xquery.xsd">
    <patient>
        <patient-id>1</patient-id>
        <name>Mary Sue</name>
        <treatment>
            <id>1</id>
            <diagnosis>Breast Cancer</diagnosis>
            <drug>Some Cancer Drug</drug>
            <provider>
                <npi>123456</npi>
                <name>Martha Susan</name>
            </provider>
        </treatment>
        <treatment>
            <id>2</id>
            <diagnosis>Fever</diagnosis>
            <drug>Anti-inflammatory</drug>
            <provider>
                <npi>789101</npi>
                <name>James Richards</name>
            </provider>
        </treatment>
    </patient>
    <patient>
        <patient-id>2</patient-id>
        <name>John Smith</name>
        <treatment>
            <id>2</id>
            <diagnosis>Prostate Cancer</diagnosis>
            <drug>Some Cancer Drug</drug>
            <provider>
                <npi>789101</npi>
                <name>James Richards</name>
            </provider>
        </treatment>
        <treatment>
            <id>3</id>
            <diagnosis>Urinary Retention</diagnosis>
            <drug>Diuretic</drug>
            <provider>
                <npi>123456</npi>
                <name>Martha Susan</name>
            </provider>
        </treatment>
    </patient>
    <patient>
        <patient-id>3</patient-id>
        <name>Gregory Barnes</name>
        <treatment>
            <id>4</id>
            <diagnosis>Prostate Cancer</diagnosis>
            <drug>Some Cancer Drug</drug>
            <provider>
                <npi>789101</npi>
                <name>James Richards</name>
            </provider>
        </treatment>
    </patient>
</tns:clinic>
